Imports System.IO
Imports System.Text

Public Class Script
    Friend Shared Sub ValidaCaracter(ByVal js As StringBuilder)
        js.Append("function ValidaCaracter(Caracter,StringValida)")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("if ( !StringValida ) StringValida = ""ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 `~!@#$%^&*()_-+={}[]|:;'<>,./?\\\"""";")
        js.Append(vbCrLf)
        js.Append("return( StringValida.toUpperCase().indexOf(Caracter.toString().toUpperCase(),0) >= 0 );")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)
    End Sub

    Friend Shared Sub findSelectEntry(ByVal js As StringBuilder)
        js.Append("function findSelectEntry( objSel, head, tail )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("with (objSel)")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("if (options.length <= 0) ")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("strKeyInBuf = '';")
        js.Append(vbCrLf)
        js.Append("return -1;")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("if ( strKeyInBuf == '' )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("return( selectedIndex = options[selectedIndex=0].text.length ? -1 : 0 );")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("if (head==UNDEFINED) head = 0;")
        js.Append(vbCrLf)
        js.Append("if (tail==UNDEFINED) tail = options.length-1;")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("var mid = Math.round( (head+tail)/2 );")
        js.Append(vbCrLf)

        js.Append("if ( strKeyInBuf.toUpperCase() == options[mid].text.substring(0,strKeyInBuf.length).toUpperCase() )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("while ( (mid>0)  && strKeyInBuf.toUpperCase() == options[mid-1].text.substring(0,strKeyInBuf.length).toUpperCase() )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("mid--;  // get the topmost matching item in the list, not just the first found")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("selectedIndex = mid;")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        'js.Append("//top.status = strKeyInBuf = options[mid].text.substring(0,strKeyInBuf.length);")
        js.Append("strKeyInBuf = options[mid].text.substring(0,strKeyInBuf.length);")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("if ( mid == Math.round( (head+tail)/2 ) ) ")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("if ( (mid==tail) || ( (mid<tail) && strKeyInBuf.toUpperCase() != options[mid+1].text.substring(0,strKeyInBuf.length).toUpperCase() ) )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        'js.Append("//top.status = strKeyInBuf = options[mid].text;  // unique match found")
        js.Append("strKeyInBuf = options[mid].text;  // unique match found")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append("return selectedIndex;")
        js.Append(vbCrLf)
        js.Append("}")

        js.Append("if ( head >= tail )  // then since no exact match was found, go back to previous strKeyInBuf (thus the length-1)")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("strKeyInBuf = strKeyInBuf.substring(0, strKeyInBuf.length - 1)")
        js.Append(vbCrLf)
        js.Append("return findSelectEntry( objSel );")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("if ( strKeyInBuf.toUpperCase() < options[mid].text.substring(0,strKeyInBuf.length).toUpperCase() )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("return findSelectEntry( objSel, head, Math.max(head,mid-1) );")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("return findSelectEntry( objSel, Math.min(mid+1,tail), tail );")
        js.Append(vbCrLf)
        js.Append("}  // end with")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)
    End Sub

    Friend Shared Sub TextBoxKeyPressFormata(ByVal js As StringBuilder)
        'js.Append("<SCRIPT LANGUAGE=JavaScript>")
        js.Append("function TextBoxKeyPressFormata(Mascara) {" & vbCrLf)
        js.Append("      var event = window.event;  // to handle both NS and IE events" & vbCrLf)
        js.Append("      var objForm = event.target ? event.target : event.srcElement;" & vbCrLf)
        js.Append("      var inputChar = String.fromCharCode(event.keyCode ? event.keyCode : event.charCode);" & vbCrLf)
        js.Append("      var iKeyCode = event.keyCode;" & vbCrLf)
        js.Append("      var texto = objForm.value;" & vbCrLf)
        js.Append("      if (texto.length >= objForm.maxLength) return false;" & vbCrLf)
        js.Append("      var textoAux = '';" & vbCrLf)
        js.Append("      for (i=0; i<Mascara.length; i++) {" & vbCrLf)
        js.Append("            if (Mascara.charAt(i) != '0' && Mascara.charAt(i) != '#' && Mascara.charAt(i) != 'a' && Mascara.charAt(i) != 'l') {" & vbCrLf)
        js.Append("                  texto = texto.replace(Mascara.charAt(i),'');" & vbCrLf)
        js.Append("            } " & vbCrLf)
        js.Append("      }" & vbCrLf)
        js.Append("      texto = texto + inputChar;" & vbCrLf)
        js.Append("      if (iKeyCode == 8)" & vbCrLf)
        js.Append("            texto = texto.substr(0, texto.length-1);" & vbCrLf)
        js.Append("      var indiceMascara = 0;" & vbCrLf)
        js.Append("      var indiceTexto = 0;" & vbCrLf)
        js.Append("      var inseriuMascara = false;" & vbCrLf)
        js.Append("      if (Mascara.charAt(0) == '#') {" & vbCrLf)
        js.Append("            indiceMascara = Mascara.length;" & vbCrLf)
        js.Append("            for (indiceTexto=texto.length -1; indiceTexto>=0; indiceTexto-- ) {" & vbCrLf)
        js.Append("                  do {" & vbCrLf)
        js.Append("                        inseriuMascara = false;" & vbCrLf)
        js.Append("                        if (indiceMascara > 0) indiceMascara = indiceMascara - 1;" & vbCrLf)
        js.Append("                        if (Mascara.charAt(indiceMascara) == '0' || Mascara.charAt(indiceMascara) == '#')  {" & vbCrLf)
        js.Append("                             if (iKeyCode > 47 && iKeyCode < 58)" & vbCrLf)
        js.Append("                                   textoAux = texto.charAt(indiceTexto) + textoAux;" & vbCrLf)
        js.Append("                             else return false;" & vbCrLf)
        js.Append("                        } else if (Mascara.charAt(indiceMascara) == 'a') {" & vbCrLf)
        js.Append("                             if ((iKeyCode > 47 && iKeyCode < 58) || (iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))" & vbCrLf)
        js.Append("                                   textoAux = texto.charAt(indiceTexto) + textoAux;" & vbCrLf)
        js.Append("                             else return false;" & vbCrLf)
        js.Append("                        } else if (Mascara.charAt(indiceMascara) == 'l') {" & vbCrLf)
        js.Append("                             if ((iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))" & vbCrLf)
        js.Append("                                   textoAux = texto.charAt(indiceTexto) + textoAux;" & vbCrLf)
        js.Append("                             else return false;" & vbCrLf)
        js.Append("                        } else {" & vbCrLf)
        js.Append("                             textoAux = Mascara.charAt(indiceMascara) + textoAux;" & vbCrLf)
        js.Append("                             inseriuMascara = true;" & vbCrLf)
        js.Append("                        }" & vbCrLf)
        js.Append("                  } while (inseriuMascara);" & vbCrLf)
        js.Append("                  if (textoAux.length >= objForm.maxLength) break;" & vbCrLf)
        js.Append("            }" & vbCrLf)
        js.Append("      } else {" & vbCrLf)
        js.Append("            for (indiceTexto=0; indiceTexto< texto.length; indiceTexto++ )   {" & vbCrLf)
        js.Append("                  iKeyCode = texto.charCodeAt(indiceTexto)" & vbCrLf)
        js.Append("                  do {" & vbCrLf)
        js.Append("                        inseriuMascara = false;" & vbCrLf)
        js.Append("                        if (Mascara.charAt(indiceMascara) == '0' || Mascara.charAt(indiceMascara) == '#') {" & vbCrLf)
        js.Append("                             if (iKeyCode > 47 && iKeyCode < 58)" & vbCrLf)
        js.Append("                                   textoAux = textoAux + texto.charAt(indiceTexto);" & vbCrLf)
        js.Append("                             else return false;" & vbCrLf)
        js.Append("                        } else if (Mascara.charAt(indiceMascara) == 'a') {" & vbCrLf)
        js.Append("                             if ((iKeyCode > 47 && iKeyCode < 58) || (iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))" & vbCrLf)
        js.Append("                                   textoAux = textoAux + texto.charAt(indiceTexto);" & vbCrLf)
        js.Append("                             else return false;" & vbCrLf)
        js.Append("                        } else if (Mascara.charAt(indiceMascara) == 'l') {" & vbCrLf)
        js.Append("                             if ((iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))" & vbCrLf)
        js.Append("                                   textoAux = textoAux + texto.charAt(indiceTexto);" & vbCrLf)
        js.Append("                             else return false;" & vbCrLf)
        js.Append("                        } else  {" & vbCrLf)
        js.Append("                             textoAux = textoAux + Mascara.charAt(indiceMascara);" & vbCrLf)
        js.Append("                             inseriuMascara = true;" & vbCrLf)
        js.Append("                        }" & vbCrLf)
        js.Append("                        if (indiceMascara < Mascara.length - 1) indiceMascara = indiceMascara + 1;" & vbCrLf)
        js.Append("                  } while (inseriuMascara);" & vbCrLf)
        js.Append("                  if (textoAux.length >= objForm.maxLength) break;" & vbCrLf)
        js.Append("            }" & vbCrLf)
        js.Append("      }" & vbCrLf)
        js.Append("      objForm.value = textoAux;" & vbCrLf)
        js.Append("      return false;" & vbCrLf)
        js.Append("}" & vbCrLf)
        'js.Append("function TextBoxKeyPressFormata(Mascara) ")
        'js.Append(vbCrLf)
        'js.Append("{")
        'js.Append(vbCrLf)
        'js.Append("	var event = window.event;  // to handle both NS and IE events")
        'js.Append(vbCrLf)
        'js.Append("	var objForm = event.target ? event.target : event.srcElement;")
        'js.Append(vbCrLf)
        'js.Append("	var inputChar = String.fromCharCode(event.keyCode ? event.keyCode : event.charCode);")
        'js.Append(vbCrLf)
        'js.Append("	var iKeyCode = event.keyCode;")
        'js.Append(vbCrLf)
        'js.Append(vbCrLf)
        'js.Append("	var texto = objForm.value;")
        'js.Append(vbCrLf)
        'js.Append("	if (texto.length >= objForm.maxLength) return false;")
        'js.Append(vbCrLf)
        'js.Append("	var textoAux = """";")
        'js.Append(vbCrLf)
        'js.Append(vbCrLf)
        'js.Append("	for (i=0; i<Mascara.length; i++)")
        'js.Append(vbCrLf)
        'js.Append("	{")
        'js.Append(vbCrLf)
        'js.Append("		if (Mascara.charAt(i) != '0' && Mascara.charAt(i) != '#' && Mascara.charAt(i) != 'a' && Mascara.charAt(i) != 'l')")
        'js.Append(vbCrLf)
        'js.Append("		{")
        'js.Append(vbCrLf)
        'js.Append("			texto = texto.replace(Mascara.charAt(i),"""");")
        'js.Append(vbCrLf)
        'js.Append("		} ")
        'js.Append(vbCrLf)
        'js.Append("	}")
        'js.Append(vbCrLf)
        'js.Append("	texto = texto + inputChar;")
        'js.Append(vbCrLf)
        'js.Append(vbCrLf)

        'js.Append("	if (iKeyCode == 8)")
        'js.Append(vbCrLf)
        'js.Append("		texto = texto.substr(0, texto.length-1);")
        'js.Append(vbCrLf)
        'js.Append(vbCrLf)
        'js.Append("	var indiceMascara = 0;")
        'js.Append(vbCrLf)
        'js.Append("	var indiceTexto = 0;")
        'js.Append(vbCrLf)
        'js.Append("	var inseriuMascara = false;")
        'js.Append(vbCrLf)
        'js.Append(vbCrLf)
        'js.Append("	if (Mascara.charAt(0) == '#')")
        'js.Append(vbCrLf)
        'js.Append("	{")
        'js.Append(vbCrLf)
        'js.Append("		indiceMascara = Mascara.length;")
        'js.Append(vbCrLf)
        'js.Append("		for (indiceTexto=texto.length -1; indiceTexto>=0; indiceTexto-- )	")
        'js.Append(vbCrLf)
        'js.Append("		{")
        'js.Append(vbCrLf)
        'js.Append("			do ")
        'js.Append(vbCrLf)
        'js.Append("			{")
        'js.Append(vbCrLf)
        'js.Append("				inseriuMascara = false;")
        'js.Append(vbCrLf)
        'js.Append("				if (indiceMascara > 0) indiceMascara = indiceMascara - 1;")
        'js.Append(vbCrLf)
        'js.Append("				if (Mascara.charAt(indiceMascara) == '0' || Mascara.charAt(indiceMascara) == '#') ")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					if (iKeyCode > 47 && iKeyCode < 58)")
        'js.Append(vbCrLf)
        'js.Append("						textoAux = texto.charAt(indiceTexto) + textoAux;")
        'js.Append(vbCrLf)
        'js.Append("					else return false;")
        'js.Append(vbCrLf)
        'js.Append("				} else if (Mascara.charAt(indiceMascara) == 'a') ")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					if ((iKeyCode > 47 && iKeyCode < 58) || (iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))")
        'js.Append(vbCrLf)
        'js.Append("						textoAux = texto.charAt(indiceTexto) + textoAux;")
        'js.Append(vbCrLf)
        'js.Append("					else return false;")
        'js.Append(vbCrLf)
        'js.Append("				} else if (Mascara.charAt(indiceMascara) == 'l') ")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					if ((iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))")
        'js.Append(vbCrLf)
        'js.Append("						textoAux = texto.charAt(indiceTexto) + textoAux;")
        'js.Append(vbCrLf)
        'js.Append("					else return false;")
        'js.Append(vbCrLf)
        'js.Append("				} else")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					textoAux = Mascara.charAt(indiceMascara) + textoAux;")
        'js.Append(vbCrLf)
        'js.Append("					inseriuMascara = true;")
        'js.Append(vbCrLf)
        'js.Append("				}")
        'js.Append(vbCrLf)
        'js.Append("			} while (inseriuMascara);")
        'js.Append(vbCrLf)
        'js.Append("			if (textoAux.length >= objForm.maxLength) break;")
        'js.Append(vbCrLf)
        'js.Append("		}")
        'js.Append(vbCrLf)
        'js.Append("	}")
        'js.Append(vbCrLf)
        'js.Append("	else")
        'js.Append(vbCrLf)
        'js.Append("	{")
        'js.Append(vbCrLf)
        'js.Append("		for (indiceTexto=0; indiceTexto< texto.length; indiceTexto++ )	")
        'js.Append(vbCrLf)
        'js.Append("		{")
        'js.Append(vbCrLf)
        'js.Append("			iKeyCode = texto.charCodeAt(indiceTexto)")
        'js.Append(vbCrLf)
        'js.Append("			do ")
        'js.Append(vbCrLf)
        'js.Append("			{")
        'js.Append(vbCrLf)
        'js.Append("				inseriuMascara = false;")
        'js.Append(vbCrLf)
        'js.Append("				if (Mascara.charAt(indiceMascara) == '0' || Mascara.charAt(indiceMascara) == '#') ")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					if (iKeyCode > 47 && iKeyCode < 58)")
        'js.Append(vbCrLf)
        'js.Append("						textoAux = textoAux + texto.charAt(indiceTexto);")
        'js.Append(vbCrLf)
        'js.Append("					else return false;")
        'js.Append(vbCrLf)
        'js.Append("				} else if (Mascara.charAt(indiceMascara) == 'a') ")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					if ((iKeyCode > 47 && iKeyCode < 58) || (iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))")
        'js.Append(vbCrLf)
        'js.Append("						textoAux = textoAux + texto.charAt(indiceTexto);")
        'js.Append(vbCrLf)
        'js.Append("					else return false;")
        'js.Append(vbCrLf)
        'js.Append("				} else if (Mascara.charAt(indiceMascara) == 'l') ")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					if ((iKeyCode > 64 && iKeyCode < 91) || (iKeyCode > 96 && iKeyCode < 123))")
        'js.Append(vbCrLf)
        'js.Append("						textoAux = textoAux + texto.charAt(indiceTexto);")
        'js.Append(vbCrLf)
        'js.Append("					else return false;")
        'js.Append(vbCrLf)
        'js.Append("				} else")
        'js.Append(vbCrLf)
        'js.Append("				{")
        'js.Append(vbCrLf)
        'js.Append("					textoAux = textoAux + Mascara.charAt(indiceMascara);")
        'js.Append(vbCrLf)
        'js.Append("					inseriuMascara = true;")
        'js.Append(vbCrLf)
        'js.Append("				}")
        'js.Append(vbCrLf)
        'js.Append("				if (indiceMascara < Mascara.length - 1) indiceMascara = indiceMascara + 1;")
        'js.Append(vbCrLf)
        'js.Append("			} while (inseriuMascara);")
        'js.Append(vbCrLf)
        'js.Append("			if (textoAux.length >= objForm.maxLength) break;")
        'js.Append(vbCrLf)
        'js.Append("		}")
        'js.Append(vbCrLf)
        'js.Append("	}")
        'js.Append(vbCrLf)
        'js.Append("	objForm.value = textoAux;")
        'js.Append(vbCrLf)
        'js.Append("	return false;		")
        'js.Append(vbCrLf)
        'js.Append("}")
        'js.Append(vbCrLf)
    End Sub

    Friend Shared Sub DropDownKeyPressBusca(ByVal js As StringBuilder)
        js.Append("function DropDownKeyPressBusca(e)")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("var event = e ? e : window.event;  // to handle both NS and IE events")
        js.Append(vbCrLf)
        js.Append("var objSelect = event.target ? event.target : event.srcElement;")
        js.Append(vbCrLf)
        js.Append("var inputChar = String.fromCharCode(event.keyCode ? event.keyCode : event.charCode);")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("if ( inputChar=='\n' || inputChar=='\r' )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        'js.Append("//top.status = objSelect.strKeyInBuf = ( objSelect.selectedIndex>-1 ? objSelect.options[objSelect.selectedIndex].text : '' );")
        js.Append("objSelect.strKeyInBuf = ( objSelect.selectedIndex>-1 ? objSelect.options[objSelect.selectedIndex].text : '' );")
        js.Append(vbCrLf)
        js.Append("objSelect.strKeyInBuf = '';")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("if ( ValidaCaracter(inputChar) && event.charCode!=0 )")
        js.Append(vbCrLf)
        js.Append("{")
        js.Append(vbCrLf)
        js.Append("if (objSelect.strKeyInBuf==UNDEFINED) objSelect.strKeyInBuf='';")
        js.Append(vbCrLf)
        js.Append("objSelect.strKeyInBuf += inputChar;")
        js.Append(vbCrLf)
        js.Append("findSelectEntry(objSelect);")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
        js.Append(vbCrLf)

        js.Append("return false;")
        js.Append(vbCrLf)
        js.Append("}")
        js.Append(vbCrLf)
    End Sub

    Public Shared Sub CriaArquivo(ByVal Caminho As String)
        Dim Arquivo As StreamWriter = File.CreateText(Caminho & "\js\insix.js")
        Dim js As New StringBuilder
        If js.Length > 0 Then js.Remove(0, js.Length)
        js.Append("var UNDEFINED;")
        js.Append(vbCrLf)

        ValidaCaracter(js)
        findSelectEntry(js)
        DropDownKeyPressBusca(js)
        TextBoxKeyPressFormata(js)

        Arquivo.Write(js.ToString())
        Arquivo.Flush()
        Arquivo.Close()
    End Sub

End Class